### ISSUE TITLE
TRTL бот для канала телешрамм

### ISSUE THREAD

**Issue by wolfimen** [turtlecoin/exile-bot#1]
Приветствую уважаемое сообщество и разработчиков! 
Ребята я заметил, что в телеграмм нет черепах, а народу сидит масса. В связи с этим родилась идея сделать канал  в телеграмме. Нужна помощь с ботом. Нужно, чтобы он показывал состояние сети, цену и капитализацию Turtlecoin. Похожее есть в дискорд. Может кто-нибудь помочь подсказкой?
С уважением wolfimen!

**Comment by brandonlehmann** [comment]
If I understood your question correctly, this message is not appropriate for this repository as it does not service Telegram. You'll find that the vast majority of Turtles and community is on Discord and/or Keybase as a backup. Telegram is not a preferred communication medium. Perhaps you'd like to come say hi at http://chat.turtlecoin.lol
